//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableCategory()
        {
            this.TableProduct = new HashSet<TableProduct>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public int CategoryCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableProduct> TableProduct { get; set; }
    }
}
