//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProduct
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int ProductPrice { get; set; }
        public string ProductBarcode { get; set; }
        public int ProductCategory { get; set; }
    
        public virtual TableCategory TableCategory { get; set; }
    }
}
